name: uitest

on:
  workflow_dispatch:
    inputs:
      target-vsix-run-id:
        description: "target vsix github action run id"
        required: true
        type: string

      target-cli-version:
        description: "target cli version or tag, like latest, beta or alpha"
        required: true
        type: string

      target-sample-ref:
        description: "target sample ref, like v1.1.0, v2.0.0 or dev"
        required: false
        type: string
        default: dev

      test-case:
        description: 'test case, e.g. ["localdebug-tab", "localdebug-bot"], Set empty to run all predefined cases'
        required: false
        type: string

      os:
        default: '["macos-latest", "ubuntu-latest", "windows-latest"]'
        description: 'os, e.g. ["macos-latest", "ubuntu-latest", "windows-latest"]'
        required: false
        type: string

      node-version:
        default: "[18]"
        description: "node version, e.g. [18]"
        required: false
        type: string

      email-receiver:
        description: "email notification receiver"
        required: false
        type: string

      source-testplan-id:
        description: "source testplan id: 24569079."
        required: false
        type: string
        default: "24569079"

      target-testplan-name:
          description: "For example: CY230919. Sync test result to this test plan."
          required: false
          type: string
  schedule:
    - cron: "0 18 * * *"

permissions:
  actions: read

jobs:
  setup:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      AUTO_TEST_PLAN_ID: ${{ github.event.inputs.source-testplan-id }}
      TARGET_TEST_PLAN_NAME: ${{ github.event.inputs.target-testplan-name }}
      DEVTUNNEL_CLIENT_ID: ${{ secrets.TEST_CLEAN_CLIENT_ID }}
      DEVTUNNEL_CLIENT_SECRET: ${{ secrets.TEST_CLEAN_CLIENT_SECRET }}
      DEVTUNNEL_TENANT_ID: ${{ secrets.TEST_CLEAN_TENANT_ID }}

    steps:
      - name: Init GitHub CLI
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token

      - name: bvt (dispatch)
        id: bvt
        if: ${{ github.event_name == 'workflow_dispatch' }}
        run: |
          echo "npm-tag=${{ github.event.inputs.target-cli-version }}" >> $GITHUB_OUTPUT
          echo "sample-ref=${{ github.event.inputs.target-sample-ref }}" >> $GITHUB_OUTPUT
          echo "branch=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          echo "vsix-run-id=${{ github.event.inputs.target-vsix-run-id }}" >> $GITHUB_ENV
          echo "target_cli_version=${{ github.event.inputs.target-cli-version }}" >> $GITHUB_ENV
          echo "email-receiver=${{ github.event.inputs.email-receiver }}" >> $GITHUB_OUTPUT

      - name: pvt (dev)
        id: pvt
        if: ${{ github.event.schedule == '0 18 * * *' }}
        run: |
          echo "npm-tag=alpha" >> $GITHUB_OUTPUT
          echo "sample-ref=dev" >> $GITHUB_OUTPUT
          echo "branch=dev" >> $GITHUB_OUTPUT
          echo "email-receiver=teamsfxqa@microsoft.com" >> $GITHUB_OUTPUT

          run_id=`gh run list --workflow cd --repo OfficeDev/TeamsFx --branch dev --json event --json databaseId --json conclusion --jq '[.[] | select(.event=="schedule") | select(.conclusion=="success")][0].databaseId'`
          echo "vsix-run-id=$run_id" >> $GITHUB_ENV
          echo "target_cli_version=alpha" >> $GITHUB_ENV

      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          ref: ${{ steps.bvt.outputs.branch || steps.pvt.outputs.branch }}

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - uses: pnpm/action-setup@v4

      - name: setup matrix
        id: setup-matrix
        working-directory: packages/tests
        run: |
          matrix=""
          if [ ! -z "${{ github.event.inputs.test-case }}" ]; then
            matrix='{"node-version": ${{ github.event.inputs.node-version }}, "test-case": ${{ github.event.inputs.test-case }}, "os": ${{ github.event.inputs.os }} }'
          else
            bash ./scripts/convert-test-case.sh ./scripts/pvt.json
            matrix=$(cat ./scripts/test-case-temp.json)
          fi

          echo "matrix=${matrix}" >> $GITHUB_OUTPUT

      - name: Download TTK
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token 
          gh run download ${{ env.vsix-run-id }} --repo OfficeDev/TeamsFx --name release

      - name: Export TTK version
        id: ttk
        run: |
          package=`find . -type f -name "*.vsix" | sed 's|.*/\(.*\)|\1|'`
          version=`echo $package | sed 's|ms-teams-vscode-extension-||' | sed 's|\.vsix||'`
          echo "package=$package" >> $GITHUB_OUTPUT
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Upload TTK to artifact
        uses: actions/upload-artifact@v4
        with:
          name: ttk
          path: |
            ./${{ steps.ttk.outputs.package }}

      - name: clean devtunnel
        run: |
          wget https://tunnelsassetsprod.blob.core.windows.net/cli/1.0.1249+67b1cd300c/linux-x64-devtunnel -O ./devtunnel
          chmod 777 ./devtunnel
          ./devtunnel user login --sp-tenant-id ${{env.DEVTUNNEL_TENANT_ID}} --sp-client-id ${{env.DEVTUNNEL_CLIENT_ID}} --sp-secret ${{env.DEVTUNNEL_CLIENT_SECRET}}
          ./devtunnel delete-all -f

    outputs:
      npm-tag: ${{ steps.bvt.outputs.npm-tag || steps.pvt.outputs.npm-tag }}
      sample-ref: ${{ steps.bvt.outputs.sample-ref || steps.pvt.outputs.sample-ref }}
      branch: ${{ steps.bvt.outputs.branch || steps.pvt.outputs.branch }}
      email-receiver: ${{ steps.bvt.outputs.email-receiver || steps.pvt.outputs.email-receiver }}
      vsix-run-id: ${{ env.vsix-run-id }}
      matrix: ${{ steps.setup-matrix.outputs.matrix }}
      ttk-package: ${{ steps.ttk.outputs.package }}
      ttk-version: ${{ steps.ttk.outputs.version }}
      target_cli_version: ${{ env.target_cli_version }}

  main:
    name: ${{ matrix.test-case }}|${{ matrix.os }}|node ${{ matrix.node-version }}|${{ github.ref_name }}
    needs: setup
    permissions:
      contents: read
    timeout-minutes: 50
    env:
      CI_ENABLED: true
      NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
      TARGET_CLI_VERSION: ${{ needs.setup.outputs.target_cli_version }}

      CLEAN_CLIENT_ID: ${{ secrets.TEST_CLEAN_CLIENT_ID }}
      CLEAN_TENANT_ID: ${{ secrets.TEST_CLEAN_TENANT_ID }}

      DEVTUNNEL_CLIENT_ID: ${{ secrets.TEST_CLEAN_CLIENT_ID }}
      DEVTUNNEL_CLIENT_SECRET: ${{ secrets.TEST_CLEAN_CLIENT_SECRET }}
      DEVTUNNEL_TENANT_ID: ${{ secrets.TEST_CLEAN_TENANT_ID }}

      M365_ACCOUNT_PASSWORD: ${{ secrets.TEST_M365_PASSWORD }}
      M365_USERNAME: "test14@xxbdw.onmicrosoft.com"
      M365_USERNAME_2: "test15@xxbdw.onmicrosoft.com"
      M365_USERNAME_3: "test16@xxbdw.onmicrosoft.com"
      M365_USERNAME_4: "test17@xxbdw.onmicrosoft.com"
      M365_USERNAME_5: "ttktest01@xxbdw.onmicrosoft.com"
      M365_DISPLAY_NAME: "ttktest"
      M365_TENANT_ID: ${{ secrets.TEST_CLEAN_TENANT_ID }}
      M365_COLLABORATOR: "haolong@xxbdw.onmicrosoft.com"

      AZURE_TENANT_ID: ${{ secrets.TEST_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.TEST_SUBSCRIPTION_ID }}
      AZURE_SUBSCRIPTION_NAME: ${{ secrets.TEST_SUBSCRIPTION_NAME }}
      AZURE_ACCOUNT_NAME: ${{ secrets.TEST_USER_NAME }}
      AZURE_ACCOUNT_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}
      STORAGE_ACCOUNT_KEY: ${{ secrets.TEST_STORAGE_ACCOUNT_KEY }}

      AZURE_OPENAI_DEPLOYMENT_NAME: "gpt-4-32k"
      AZURE_OPENAI_ENDPOINT: "https://aoai-jasozdr.openai.azure.com/"
      AZURE_OPENAI_EMBEDDING_DEPLOYMENT: "text-embedding-ada-002"

      TEAMSFX_DEV_TUNNEL_TEST: true
      TEAMSFX_TELEMETRY_TEST: true
    strategy:
      fail-fast: false
      max-parallel: 80
      matrix: ${{ fromJson(needs.setup.outputs.matrix) }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Set m365 account (unix)
        run: |
          echo abc

      - name: Set m365 account2
        run: |
          echo1 abc

  test-plan-update:
    needs: main
    if: ${{ always()}}
    environment: engineering
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    env:
      AUTO_TEST_PLAN_ID: ${{ github.event.inputs.source-testplan-id }}
    steps:
      - name: trigger rerun workflow3
        run: |
          echo abc
          echo ${{ github.event.inputs.test-case }}
          echo abc2 

  rerun:
    permissions:
      actions: write
    needs: main
    if: ${{ ((github.event_name == 'workflow_dispatch' && github.event.inputs.test-case == '') || ((github.event_name == 'workflow_dispatch' && github.event.inputs.target-cli-version == 'rc')) && failure() && github.run_attempt < 5 }}
    runs-on: ubuntu-latest
    steps:
      - name: trigger rerun workflow2
        run: |
          echo abc
          echo ${{ github.event.inputs.test-case }}
          echo abc2

      - name: trigger rerun workflow
        run: |
          curl \
           -X POST \
           -H "Accept: application/vnd.github+json" \
           -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}"\
           -H "X-GitHub-Api-Version: 2022-11-28" \
           https://api.github.com/repos/${{ github.repository }}/actions/workflows/rerun.yml/dispatches \
           -d '{"ref":"${{ github.ref_name }}","inputs":{"run_id":"${{ github.run_id }}", "max_attempts":"5"}}'

  report:
    if: ${{ (github.event_name == 'workflow_dispatch' && needs.setup.outputs.email-receiver) || (github.event_name == 'schedule' && (success() || (failure() && github.run_attempt >= 5))) }}
    needs: [setup, main]
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3
